const data = {
  products: [
    {
      name: 'Nike Slim Shirk',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      constInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
        name: 'Addidas Slim Shirk',
        slug: 'nike-slim-shirt',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 120,
        constInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
    {
        name: 'Addidas Fit Pant',
        slug: 'adidas-fit-pant',
        category: 'Pants',
        image: '/images/p4.jpg',
        price: 64,
        constInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        name: 'Nike Slim Shirk',
        slug: 'nike-slim-shirt',
        category: 'Pants',
        image: '/images/p3.jpg',
        price: 120,
        constInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
  ],
};
